# Generated by Django 5.2.1 on 2025-05-23 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('symbol', models.CharField(max_length=10, verbose_name='Символ')),
                ('network', models.CharField(max_length=50, verbose_name='Сеть')),
            ],
            options={
                'verbose_name': 'Криптовалюта',
                'verbose_name_plural': 'Криптовалюты',
            },
        ),
        migrations.CreateModel(
            name='GuestAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=255, verbose_name='Имя действия')),
                ('can_execute', models.BooleanField(default=True, verbose_name='Можно выполнять')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Гостевое действие',
                'verbose_name_plural': 'Гостевые действия',
            },
        ),
        migrations.CreateModel(
            name='GuestPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255, verbose_name='Имя страницы')),
                ('can_view', models.BooleanField(default=True, verbose_name='Можно просматривать')),
                ('can_register', models.BooleanField(default=False, verbose_name='Можно зарегистрироваться')),
                ('can_login', models.BooleanField(default=False, verbose_name='Можно войти')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Гостевое разрешение',
                'verbose_name_plural': 'Гостевые разрешения',
            },
        ),
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=255, verbose_name='Токен сессии')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('last_activity', models.DateTimeField(verbose_name='Последняя активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Гостевая сессия',
                'verbose_name_plural': 'Гостевые сессии',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255, verbose_name='Название страницы')),
                ('can_view', models.BooleanField(default=True, verbose_name='Можно просматривать')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('role', models.CharField(choices=[('guest', 'Гость'), ('user', 'Пользователь'), ('admin', 'Администратор')], default='user', max_length=10, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='GuestPermissionsActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.guestaction', verbose_name='Гостевое действие')),
                ('guest_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.guestpermission', verbose_name='Гостевое разрешение')),
            ],
            options={
                'verbose_name': 'Действие разрешения',
                'verbose_name_plural': 'Действия разрешений',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тикет поддержки',
                'verbose_name_plural': 'Тикеты поддержки',
            },
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_pairs', to='main.cryptocurrency', verbose_name='Базовая валюта')),
                ('quote_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_pairs', to='main.cryptocurrency', verbose_name='Котируемая валюта')),
            ],
            options={
                'verbose_name': 'Торговая пара',
                'verbose_name_plural': 'Торговые пары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('buy', 'покупка'), ('sell', 'продажа')], max_length=10, verbose_name='Тип')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Цена')),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Объём')),
                ('status', models.CharField(choices=[('pending', 'в ожидании'), ('partially_completed', 'частично завершено'), ('completed', 'завершено'), ('cancelled', 'отменено')], max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tradingpair', verbose_name='Торговая пара')),
            ],
            options={
                'verbose_name': 'Ордер',
                'verbose_name_plural': 'Ордеры',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'депозит'), ('withdrawal', 'вывод'), ('trade', 'торговля')], max_length=10, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Сумма')),
                ('fee', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Комиссия')),
                ('total_amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Итоговая сумма')),
                ('status', models.CharField(choices=[('pending', 'в ожидании'), ('completed', 'завершено'), ('cancelled', 'отменено')], max_length=20, verbose_name='Статус')),
                ('timestamp', models.DateTimeField(verbose_name='Дата и время')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_refunded', models.BooleanField(default=False, verbose_name='Возвращено')),
                ('counter_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_transactions', to='main.order')),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cryptocurrency', verbose_name='Криптовалюта')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Сумма')),
                ('symbol', models.CharField(max_length=10, verbose_name='Символ')),
                ('type', models.CharField(max_length=10, verbose_name='Тип')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('changed_at', models.DateTimeField(verbose_name='Дата изменения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transaction', verbose_name='Транзакция')),
            ],
            options={
                'verbose_name': 'История транзакции',
                'verbose_name_plural': 'Истории транзакций',
            },
        ),
        migrations.CreateModel(
            name='UserPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_date', models.DateTimeField(verbose_name='Дата участия')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.promotion', verbose_name='Акция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участие в акции',
                'verbose_name_plural': 'Участия в акциях',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Баланс')),
                ('last_transaction_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней транзакции')),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cryptocurrency', verbose_name='Криптовалюта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Кошелёк',
                'verbose_name_plural': 'Кошельки',
            },
        ),
    ]
