# Generated by Django 5.2.1 on 2025-05-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'открыто'), ('closed', 'закрыто')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'в ожидании'), ('completed', 'завершено'), ('cancelled', 'отменено')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='type',
            field=models.CharField(choices=[('deposit', 'депозит'), ('withdrawal', 'вывод'), ('trade', 'торговля')], max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор')], default='user', max_length=10, verbose_name='Роль'),
        ),
    ]
