# Generated by Django 5.2.1 on 2025-05-24 18:05

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_supportticket_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Гостевое действие', 'verbose_name_plural': 'Гостевые действия'},
        ),
        migrations.AlterModelOptions(
            name='guestpermission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Гостевое разрешение', 'verbose_name_plural': 'Гостевые разрешения'},
        ),
        migrations.AlterModelOptions(
            name='guestsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Гостевая сессия', 'verbose_name_plural': 'Гостевые сессии'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ордер', 'verbose_name_plural': 'Ордеры'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-created_at'], 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-start_date'], 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Тикет поддержки', 'verbose_name_plural': 'Тикеты поддержки'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterModelOptions(
            name='transactionhistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'История транзакции', 'verbose_name_plural': 'Истории транзакций'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userpromotion',
            options={'ordering': ['-participation_date'], 'verbose_name': 'Участие в акции', 'verbose_name_plural': 'Участия в акциях'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-last_transaction_date'], 'verbose_name': 'Кошелёк', 'verbose_name_plural': 'Кошельки'},
        ),
        migrations.AlterField(
            model_name='guestsession',
            name='session_token',
            field=models.CharField(default=main.models.generate_guest_token, max_length=255, verbose_name='Токен сессии'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний вход'),
        ),
        migrations.AlterField(
            model_name='userpromotion',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main.promotion', verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='userpromotion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_promotions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
