# Generated by Django 5.2.1 on 2025-06-02 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_guestaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestpermission',
            name='actions',
            field=models.ManyToManyField(related_name='permissions', through='main.GuestPermissionsActions', to='main.guestaction', verbose_name='Доступные действия'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='users',
            field=models.ManyToManyField(related_name='promotions', through='main.UserPromotion', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='userpromotion',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершил'), ('cancelled', 'Отменил участие')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpromotion',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.promotion', verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='userpromotion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='userpromotion',
            unique_together={('user', 'promotion')},
        ),
    ]
