# Generated by Django 5.2.1 on 2025-06-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_guestpermission_actions_promotion_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/'),
        ),
        migrations.AlterField(
            model_name='userpromotion',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('completed', 'Завершил'), ('cancelled', 'Отменил участие')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
