# Generated by Django 5.2.1 on 2025-06-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_transactionreport_alter_promotion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
