# Generated by Django 5.2.1 on 2025-06-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_promotion_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='Текущий курс'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Веб-сайт'),
        ),
    ]
