# Generated by Django 5.2.1 on 2025-06-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cryptocurrency_price_tradingpair_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='price_at_moment',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Цена на момент сделки'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='price_at_moment',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Цена на момент изменения'),
        ),
    ]
