# Generated by Django 5.2.1 on 2025-06-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_transaction_price_at_moment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingpair',
            name='price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='price_at_moment',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='price_at_moment',
        ),
    ]
