# Generated by Django 5.2.1 on 2025-06-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_tradingpair_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_fee_percent', models.DecimalField(decimal_places=2, default=0.2, max_digits=5)),
                ('withdrawal_limit_daily', models.DecimalField(decimal_places=8, default=5, max_digits=20)),
                ('min_order_value', models.DecimalField(decimal_places=8, default=10, max_digits=20)),
            ],
            options={
                'verbose_name': 'Настройки биржи',
            },
        ),
    ]
