# Generated by Django 5.2.1 on 2025-06-13 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_exchangesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeSettings',
        ),
    ]
