# Generated by Django 5.2.1 on 2025-06-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_order_trading_pair_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='test_field',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Тестовое поле'),
        ),
    ]
