# Generated by Django 5.2.1 on 2025-06-14 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_cryptocurrency_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='test_field',
        ),
    ]
