# Generated by Django 5.2.1 on 2025-06-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_cryptocurrency_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20, verbose_name='Цена'),
        ),
    ]
