# Generated by Django 5.2.1 on 2025-06-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_cryptocurrency_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=15, null=True, verbose_name='Цена'),
        ),
    ]
