# Generated by Django 5.2.1 on 2025-06-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_cryptocurrency_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=15, verbose_name='Цена'),
        ),
    ]
